Added menuItem in navigation folder
grupadotnet/eAkademik pull request #25
Opened 2022-04-15 20:03 UTC by Nieznany4321

![Screenshot 2022-04-15 215109](https://user-images.githubusercontent.com/59314982/163626610-ead654dc-bf48-49a8-ac95-98981bc9abbe.png)
Nom to w sumie nie wiem czy może być taka ikonka czy dowolna
![278396951_315948347318713_4990761925022399701_n](https://user-images.githubusercontent.com/59314982/163626716-32dec200-033b-4f77-a295-f7a6242086b1.png)
nom a tu po najechaniu myszki, ciemniejszy kolor i napis z ikonkąna biało

2022-04-17 16:55 UTC, JacobChwastek reviewed
Wrzuciłbym .vscode do .gitignore

2022-04-18 13:45 UTC, jaroslawlesniak commented
@JacobChwastek ten .vscode będzie ogarnięty w osobnym tasku. Który to wszystko uporządkuje

2022-04-18 14:04 UTC, jaroslawlesniak requested changes
Wygląd tego komponentu (padding, itp) nie zgadza się z przykładową aplikacją. Tu masz linka do pierwowzoru: https://github.com/grupadotnet/eAkademik/wiki/Wygl%C4%85d-aplikacji

2022-04-18 14:04 UTC, jaroslawlesniak commented on frontend/src/components/navigation/menuItem.tsx
> +function MenuItem(){
Trochę w inny sposób trzeba to ogarnąć. Zerknij sobie jak wygląda stylowanie przycisku w `src/components/buttons/Button.tsx`

W typ przypadku będzie to coś takiego:
`
import { MenuItem as AMenuItem } from 'antd';

const MenuItem = styled(AMenuItem)
`

2022-04-18 14:04 UTC, jaroslawlesniak commented on frontend/src/components/navigation/menuItem.tsx
> +
Nie liczy się ilość linijek tylko ich jakoś. Puste linijki są do usunięcia 🙈

2022-04-18 14:04 UTC, jaroslawlesniak commented on frontend/src/components/navigation/menuItem.tsx
> +export default MenuItem;
Każdy plik powinien kończyć się znakiem nowej linii (dodać enter na końcu pliku)

2022-04-20 16:09 UTC, jaroslawlesniak commented
Jakieś konflikty wleciały, jakbyś mógł je najpierw rozwiązać. Bo może się coś pozmieniać w międzyczasie

2022-04-24 17:26 UTC, merged